# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  tag: 1.0.0--$(Build.BuildId) 

stages:

- stage: Code_Analysis
  displayName: Code Analysis
  jobs:
  - job: codeAnalysis
    steps:
    - script: echo Code Analysis
- stage: Build_Package
  displayName: Build Package
  jobs:
  - job: buildPackage
    steps:
    - script: echo Build Package
- stage: Build_Image
  displayName: Build and Push Image
  jobs:
  - job: buildImage
    steps:
    - script: echo Build Image
- stage: Deploy_Dev
  displayName: Deploy Dev
  jobs:
  - job: deployDev
    steps:
    - script: echo Deploy Dev
