# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- master

pool:
  vmImage: ubuntu-latest

variables:
  tag: 1.0.0--$(Build.BuildId) 
  PROJECT_NAME: java-kubernetes
  PROJECT_KEY: pruthvi1987_java-kubernetes
  SONAR_TOKEN: 92edc45840350f9a713dec10cf172bc9d5c56eb3
  BRANCH: master

stages:

- stage: Code_Analysis
  displayName: Code Analysis
  jobs:
  - job: codeAnalysis
    steps:
    - script: echo Code Analysis
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'mvn sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.login=$SONAR_TOKEN -Dsonar.sources=./src -Dsonar.java.binaries=**/*.java -Dsonar.projectName=$PROJECT_NAME -Dsonar.branch.name=$BRANCH'

- stage: Build_Package
  displayName: Build Package
  jobs:
  - job: buildPackage
    steps:
    - script: echo Build Package
- stage: Build_Image
  displayName: Build and Push Image
  jobs:
  - job: buildImage
    steps:
    - script: echo Build Image
- stage: Deploy_Dev
  displayName: Deploy Dev
  jobs:
  - job: deployDev
    steps:
    - script: echo Deploy Dev
