# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- master

pool:
  vmImage: ubuntu-latest

variables:
  tag: 1.0.0-$(Build.BuildId) 
  PROJECT_NAME: java-kubernetes
  PROJECT_KEY: pruthvi1987_java-kubernetes
  SONAR_TOKEN: 92edc45840350f9a713dec10cf172bc9d5c56eb3
  BRANCH: master

stages:

- stage: Code_Analysis
  displayName: Code Analysis
  jobs:
  - job: codeAnalysis
    steps:
    - task: CmdLine@2
      inputs:
        script: 'mvn sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.login=$SONAR_TOKEN -Dsonar.sources=./src -Dsonar.java.binaries=**/* -Dsonar.projectName=$PROJECT_NAME -Dsonar.branch.name=$BRANCH'

- stage: Build_Package
  displayName: Build Package
  jobs:
  - job: buildPackage
    steps:
    
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
       
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: |
          **/*.jar
          Dockerfile
          k8s/**
        TargetFolder: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()
      
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: package'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: package
      condition: succeededOrFailed()
    

- stage: Build_Image
  dependsOn: Build_Package
  displayName: Build and Push Image
  jobs:
  - job: buildImage
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'package'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'docker build -f $(System.ArtifactsDirectory)/package/Dockerfile -t azcoderegistry.azurecr.io/java-kubernetes:$(tag) target'
        workingDirectory: '$(System.ArtifactsDirectory)/package/target'
        
- stage: Deploy_Dev
  displayName: Deploy Dev
  jobs:
  - job: deployDev
    steps:
    - script: echo Deploy Dev
